-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mar. 20 juin 2023 à 02:01
-- Version du serveur :  5.7.31
-- Version de PHP : 7.4.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `formation`
--

-- --------------------------------------------------------

--
-- Structure de la table `articles`
--

DROP TABLE IF EXISTS `articles`;
CREATE TABLE IF NOT EXISTS `articles` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `pic` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `articles`
--

INSERT INTO `articles` (`id`, `title`, `slug`, `content`, `pic`, `created_at`, `updated_at`) VALUES
(1, 'Accusamus veritatis enim ut quo ratione dignissimos error.', 'Dolores nisi doloremque dolorum dolore deleniti pariatur nesciunt. Aut consequuntur delectus nobis rerum dolor amet nostrum. Qui velit tempore ut ipsa. Error adipisci qui veritatis eos non non. Qui fugit aspernatur et fuga ut ab.', 'Voluptas enim at cumque illum deleniti. Vel eos magni corrupti quis iure. Adipisci est libero commodi voluptate voluptatum ut et. Facere qui sit quia.\n\nQuidem sed doloribus odit et consequatur ducimus. Porro voluptatem nemo et quia. Hic sit maiores velit officia temporibus rerum. Est error illo dolorem. Inventore dolores voluptatibus magni est dignissimos.\n\nFugiat nam et quas est. Occaecati et aut molestias reiciendis aperiam. Repellat et quaerat ipsam. Quisquam enim odio aliquam dicta.\n\nOdio animi tempore est ducimus dolore fugit. Ad qui reprehenderit autem modi iure. Asperiores fugit vel sit inventore.\n\nAtque omnis vel dolores. Voluptatem quasi debitis nihil dolores. Repellendus debitis fuga totam eos. Laudantium illo accusamus fuga beatae nihil quo.\n\nVoluptas officia porro nesciunt numquam suscipit consequatur omnis. Ullam autem vero et eum. Quo deleniti nobis excepturi ea ut.\n\nEsse incidunt sapiente fugit neque. Corporis dolores omnis consequatur minus maiores mollitia at. Facilis et assumenda alias numquam sit. Iure laudantium minus suscipit ratione.\n\nId molestias molestiae officiis similique reiciendis architecto. Occaecati magni fugiat perspiciatis nihil illum. Repudiandae aut dolor occaecati aut vitae dolores eos. Molestiae et deserunt maiores praesentium veniam repudiandae minima.\n\nCorrupti et id fuga voluptatem aperiam aspernatur nihil. Nemo odit sint tempora adipisci alias voluptatum repudiandae. Dolor sunt inventore quis beatae minima reprehenderit alias. Unde dolores aut dolores at ut qui est.\n\nConsequatur voluptatem explicabo dolorem sed. Minus temporibus amet sit excepturi eligendi. Labore placeat architecto quia cupiditate eos expedita illo. Eos repellat amet incidunt ut laboriosam maiores iure.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(2, 'Corrupti occaecati quidem placeat optio.', 'Ipsam officia id quasi id. Eveniet quas minima distinctio. Dolores ipsa error nobis ducimus.', 'Ab consequatur vitae consequatur libero veritatis cumque non. Autem est est et dolorem consequatur optio. Iure est rerum pariatur quo.\n\nCupiditate provident quasi non expedita beatae voluptatem nihil. Aliquam eaque ea excepturi incidunt blanditiis autem ut. Consequatur voluptas incidunt quam. Reiciendis facilis et sed sapiente.\n\nDeserunt necessitatibus quis ipsum ipsa modi aperiam velit. Perspiciatis non consequatur tempore et. Tempore in et dolor autem dolor voluptatibus ut. Dolorem cupiditate perferendis ipsum ut.\n\nRepellendus molestiae maxime sed nostrum. Consectetur consequatur numquam numquam eaque explicabo sapiente eum. Reprehenderit officiis possimus sed nisi et quam.\n\nVoluptatem possimus ea quis aut nam. Cum explicabo temporibus harum minima. Molestias quaerat ea porro non rerum sit quae. At fugiat temporibus vel sed.\n\nDolorem dolorem consequuntur et nisi. Enim quia voluptate quia. Facilis et sapiente earum officiis.\n\nOdit praesentium hic nostrum. Libero ad ducimus consequatur dolores fuga autem. Quibusdam quia et occaecati id qui commodi nulla.\n\nVeniam natus delectus quasi at assumenda. Recusandae eos earum dolorem sit veniam possimus. Aut ut ullam voluptatem sed blanditiis. Ad fugit officiis quaerat vitae necessitatibus totam ab eos.\n\nFacere asperiores sit neque ut qui. Quibusdam repellendus exercitationem amet quis non. Iure corrupti voluptas qui ea ut distinctio.\n\nVel et earum mollitia. Ut ratione tempora natus nesciunt quam iusto quis enim.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(3, 'Quis rerum debitis placeat qui sunt nostrum totam commodi.', 'Culpa est quos voluptates omnis dolor perferendis voluptas dicta. Dolorum itaque minus itaque perspiciatis inventore enim. In aliquid tempora aliquid enim vitae. Ipsam sed nobis molestias impedit suscipit sed.', 'Maxime quo molestiae expedita inventore. Sit laboriosam veniam omnis culpa. Molestiae iste sit voluptate provident. Sed temporibus voluptatibus quo enim occaecati.\n\nUt optio et voluptatem rerum quis distinctio sit. Cupiditate repellat ut veritatis. Reprehenderit commodi consequatur molestiae laboriosam.\n\nTempore quia aliquid facilis corporis sit et. Harum reiciendis qui porro id voluptatibus. Omnis aut maiores soluta et sed soluta nisi beatae.\n\nRerum aut ut aut. Minima nisi omnis tenetur voluptas nulla perspiciatis. Fugit omnis fuga aut exercitationem.\n\nVitae et quia nostrum minima hic. Qui assumenda exercitationem sed.\n\nEaque beatae incidunt nam dolores. Assumenda perferendis repellendus dolores suscipit alias.\n\nRecusandae quisquam non culpa est et quo non. Earum omnis dignissimos voluptatum praesentium et dolor magni. Doloribus tempora architecto expedita labore facilis ut. Porro voluptatum eum quae at.\n\nExplicabo occaecati ut rem. Architecto distinctio tempore nulla vitae explicabo. Quia est culpa non veniam.\n\nExercitationem enim voluptas id sequi asperiores mollitia. Laudantium dolorem beatae ad atque qui. Minus facilis explicabo illum.\n\nAliquam suscipit cum et qui laboriosam est magnam. Veniam similique sed ea ab et ipsa. Modi aut distinctio blanditiis qui et est.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(4, 'Sapiente esse est harum non.', 'Blanditiis distinctio et perspiciatis magni ab id aspernatur. Ut ipsum ipsam quia ex quidem et quibusdam. Doloribus corporis rerum illum iure qui assumenda dolorem. Iste ipsum velit necessitatibus est harum voluptatem magnam.', 'Quia quibusdam assumenda atque consectetur eius quo vel. Nesciunt sit nulla fugiat et aut. Cupiditate voluptatem non illum debitis molestias a. Enim dolor dicta minus.\n\nConsequatur ipsam adipisci consequatur sit ut. Vel ipsa vero quod eum laudantium. Accusamus voluptatem amet expedita pariatur eaque et dolorem.\n\nEt reprehenderit est et quisquam voluptatem. Unde sit voluptas rerum voluptatem nemo nesciunt. Magnam rerum qui est.\n\nFugiat ipsum consequatur velit ipsam qui. Repellat recusandae itaque laboriosam quaerat cumque doloribus doloribus. Velit ut ut nostrum sit facilis tempore.\n\nAccusamus dolores qui et necessitatibus pariatur rerum perspiciatis. Est voluptatem autem officia nostrum. Voluptatem quo laudantium ullam et ut et aperiam eos.\n\nEligendi id asperiores vel consectetur. Est sequi nihil ducimus odio esse magnam maxime. Qui rerum consectetur soluta provident dolorum temporibus voluptatum.\n\nIusto molestiae impedit sint et. Maiores et sit qui qui qui commodi.\n\nQuo velit sint voluptatem sequi. Eos rem in molestias iusto. Sunt repudiandae porro magni natus tempore sint quibusdam. Neque qui perspiciatis vitae aut.\n\nAut similique corporis impedit ipsa. Cupiditate occaecati laborum minima aut inventore soluta. Nesciunt et dolores consectetur sed.\n\nVoluptate totam delectus architecto perferendis nostrum optio culpa sint. Ea vero quam aut tenetur ex. Sapiente corrupti sit tempora sit numquam molestiae.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(5, 'Quos qui commodi rerum suscipit enim omnis.', 'Nisi quasi sequi doloribus id. Ut sed architecto rem fugiat nobis. Laboriosam porro ut vel nam dolorum tenetur itaque. Excepturi voluptatem repellendus aliquam quae aut corrupti.', 'Voluptatibus rerum ipsa fuga. Cum nihil sapiente voluptatem dolor quam. Eaque aut doloremque in et assumenda eos ipsa voluptatem.\n\nDolor quis aut eum. Porro unde nostrum expedita numquam sit in nihil. Enim autem quisquam velit magni voluptas accusantium facere. Quia vitae est consequuntur. Iusto quia accusamus quod.\n\nRepellat beatae assumenda consectetur consectetur magnam rerum. Et inventore perferendis blanditiis magni minus. Tenetur consequatur perspiciatis velit vero odio perferendis quia. Facere mollitia rerum est aut a ea praesentium aut.\n\nEarum sed qui sunt nemo sed. Provident aut est blanditiis eum nulla voluptate expedita. Labore natus nam officia velit. Quis eius necessitatibus ipsa.\n\nNumquam beatae est dolorem et non. Aut aut qui voluptate quo. Id fuga et soluta et maiores temporibus. Quaerat adipisci ut sed nobis placeat. Ipsum sunt ut laboriosam.\n\nEum sed impedit perferendis placeat. Esse aspernatur voluptas facilis vel aliquam aut quaerat.\n\nNecessitatibus repudiandae voluptatum expedita illo. Quis ipsa quam eaque dolorum saepe fugiat. Optio iste deleniti facilis et voluptatem sed. Nesciunt iure aut ex non.\n\nSit labore incidunt inventore fuga facere maxime cum et. Voluptates officia dolore qui aut voluptatem consequuntur. Magnam ut porro quidem dolor.\n\nAut dolorem consequuntur et minus et dignissimos eligendi. Commodi similique voluptas dicta delectus. Numquam ut et suscipit ea.\n\nQui repellat est odit quasi. Eius aperiam quia saepe nemo. Culpa laborum ullam in consequatur perferendis consequatur et consequatur.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(6, 'Beatae laborum ratione quos commodi sapiente dolorem sunt illum.', 'Ullam est omnis voluptas alias dolorum voluptatum. Velit iure sed aut nam.', 'Perspiciatis est excepturi natus incidunt amet. Eum et et quia enim omnis earum.\n\nNihil distinctio occaecati ipsa eius. Ad doloribus quasi quia natus exercitationem quisquam autem. Amet qui aliquam ipsam mollitia qui a. Veritatis soluta voluptas quia quo reiciendis architecto non. Aut qui fugiat fugit inventore assumenda.\n\nRatione fugit sed totam. Et architecto natus a asperiores. Qui aut labore ut. Deleniti sunt facilis laudantium ex modi dolor.\n\nOccaecati cupiditate iure doloribus laudantium eaque est. Voluptas et velit delectus et ex quae. Velit ratione est rerum nesciunt et.\n\nAut iure harum quos numquam recusandae necessitatibus nesciunt aut. Amet possimus enim similique reprehenderit voluptates cumque. Laborum qui sed porro sed. Consectetur qui sunt veritatis non reiciendis.\n\nEt amet dolor reiciendis odit non vero. Magni vel est necessitatibus recusandae harum accusamus. Expedita dignissimos totam rerum blanditiis omnis sed eveniet voluptas.\n\nIn sapiente quae iusto tempora aut tempora. Iusto et fuga quae tenetur assumenda. Doloribus repudiandae ipsam non dolorum. Amet veritatis unde consequuntur animi voluptatem autem porro.\n\nDeserunt repellendus debitis qui occaecati et libero. Enim facere suscipit odio est nisi facere. Non et fuga labore repellat autem aspernatur consequatur ab. Reprehenderit nesciunt atque debitis aliquam. Vitae ullam dolor tempora laborum nihil corporis.\n\nOptio tenetur molestiae et voluptatem quos officiis. Perspiciatis odit exercitationem quas ut iure beatae. Aut voluptas accusantium aut.\n\nIste accusantium quia voluptates ea aut distinctio excepturi. Itaque autem ex nemo cum. Aperiam deleniti magni qui aut. Ad corrupti ex eos sit consequatur.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(7, 'Quia in qui eos sed illum laudantium.', 'Tempora cumque voluptatibus cupiditate consequatur ullam accusamus dolor. Et molestias id in inventore. Odio nostrum qui a quisquam cumque. Et autem facilis dolorum et ut sint ut.', 'Qui eos ratione quo et fugit. Labore quo deserunt saepe quia et. Sequi ut enim tempora est sed aut perferendis. Rerum laborum omnis quas provident et omnis.\n\nItaque magni assumenda distinctio quibusdam vitae. Ex dolore nemo quas et perferendis dignissimos. Quod tempore voluptatem impedit voluptatem quis placeat id. In consequuntur similique praesentium harum quis sed et consequatur.\n\nHarum maxime officia impedit nemo modi et et nihil. Exercitationem eius architecto totam voluptatibus voluptatem sit eius. Quia modi harum dignissimos corporis.\n\nUnde expedita aut error nemo et minima et. Et tempora repellendus itaque. Cum nobis blanditiis est.\n\nPossimus suscipit doloremque dignissimos id. Natus eum voluptas voluptate ullam ut. Accusantium dignissimos et est quia.\n\nExercitationem perspiciatis quia placeat autem aut ut quam similique. Sapiente voluptate iste et eaque ex vero.\n\nNumquam doloribus ducimus quaerat non. Ducimus quae ipsa nobis voluptas quia et. Quasi enim ea voluptas totam.\n\nMollitia voluptatem vitae dolorem ut est. Unde rerum at et fugiat ex aut ut. Expedita temporibus doloremque optio iure. Fugiat sunt ad aspernatur error esse est.\n\nTenetur cum odit officiis voluptas voluptatem deserunt. Voluptas at voluptas quo. Delectus magnam non quia distinctio ut ut.\n\nReprehenderit unde qui beatae harum et aperiam qui. Ullam explicabo et rerum fugit enim rerum et. Alias unde vitae commodi numquam cumque explicabo.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(8, 'Temporibus illo ducimus et sit rerum rem doloremque.', 'Ipsa fuga ullam cumque. Consequatur dolorem et sed perspiciatis iusto et dolorem. A iusto doloribus repudiandae.', 'Eaque id quam aut nesciunt est maiores. Voluptas repudiandae explicabo aspernatur recusandae voluptas numquam. Labore qui voluptas ex iusto. Recusandae placeat qui nesciunt dignissimos.\n\nExplicabo labore eum tempore iste. Est facere amet magnam dolorem ea corporis optio ut. Omnis culpa ea ut molestiae in. Laboriosam illo sint molestiae illum repellendus. Qui id velit eveniet quia voluptate fugit facere.\n\nEx earum voluptatibus quis quae ipsam. Consectetur est doloremque aut omnis inventore. Possimus similique eaque eum deserunt qui molestias non.\n\nBlanditiis aspernatur consectetur quae est ut. Quaerat magni distinctio reprehenderit quo omnis repellat ab doloribus. Eum ducimus consequuntur voluptas illum.\n\nSed aspernatur voluptate et ea. Pariatur est reprehenderit praesentium unde illo consequatur doloremque nostrum. Voluptatum sed modi in aut sit voluptas quia qui. Sint autem sit ratione.\n\nProvident nobis dolore tenetur. Culpa reiciendis tenetur reiciendis aut adipisci autem. Pariatur nesciunt autem eligendi et pariatur voluptas natus. Voluptas ut minima asperiores quaerat non possimus.\n\nExercitationem quod recusandae repellendus quo omnis ex occaecati. Cumque delectus non omnis odio ipsa. Neque aut illo quod suscipit quidem voluptatem delectus laudantium. Saepe est debitis tempora quae odio libero labore.\n\nEst facilis non nisi sed et voluptatibus. Eum beatae rerum mollitia soluta aut enim labore. Ipsum et sint ad cumque totam enim.\n\nTenetur minus sequi dolor accusantium quo dolorum similique. Eius dignissimos officiis sint neque iste. Non eveniet reprehenderit itaque non sint iusto voluptatem inventore.\n\nFugit occaecati possimus voluptas corrupti. Iure voluptas repudiandae omnis quia non aperiam. Eveniet sed reprehenderit molestiae. Deleniti et earum accusamus aut beatae eum.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(9, 'Fugiat occaecati odit laudantium et et et perferendis.', 'Sunt officiis porro architecto ullam. Quia corporis rerum nemo facilis sint deleniti atque. Ut est et sit.', 'Et voluptatem nostrum unde. Nesciunt itaque consequatur ab non. Harum neque cum sint voluptas rem velit voluptatem.\n\nMagni numquam sed at eligendi animi pariatur. Voluptatem quasi inventore voluptatibus. Delectus ea est reprehenderit atque illo libero.\n\nError similique incidunt debitis minima facilis repellat ut. Esse aperiam dolore sunt et. Voluptatibus iusto laudantium dolores nam facilis eum aut.\n\nEnim voluptas aspernatur vero consequuntur natus quam quia. Voluptatem autem atque dolores et amet. Ab ea quis iure facilis rerum dolore.\n\nEst ratione molestiae aut aspernatur occaecati esse. Doloremque quis quia qui. Consequatur sit voluptatibus quos qui. Explicabo placeat inventore quis.\n\nEt culpa veritatis pariatur consequuntur. Voluptas id itaque quia quibusdam. Omnis et nam provident nesciunt. Rerum ratione velit doloremque et quisquam quo autem nostrum. Ipsum quaerat qui nihil consequuntur ut tempore.\n\nNulla eligendi quisquam quasi. In enim eos veniam accusamus iure sed atque. Atque vel facilis omnis esse. Eos et nobis rem quos.\n\nDelectus aliquid vero atque voluptas. Quod alias porro distinctio sequi odit quos. Quod fugiat est laboriosam. Et dolore nobis nam veritatis culpa aspernatur.\n\nFacere sapiente dolores asperiores ut enim aut ut. Laboriosam incidunt natus est modi corporis. Velit numquam quidem molestias dolor nisi exercitationem. Dolor quaerat quia error ut possimus qui.\n\nLabore excepturi qui temporibus et nostrum quam aperiam facere. Eum vero illum eaque tempore assumenda. Quidem recusandae vel velit sit at. Enim voluptate quibusdam consequatur modi. Magni eos vel cum doloremque.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(10, 'Voluptatum culpa est dolorem.', 'Illum autem odit rerum voluptas animi necessitatibus pariatur. Doloremque architecto vitae ut nisi molestiae placeat. Beatae cumque incidunt iusto sit possimus aut dolor. Eius nihil enim quod ab ex accusamus. Sed quia recusandae consequatur impedit explicabo.', 'Perspiciatis a enim quae et unde eos asperiores aut. Praesentium et molestiae quam. Explicabo neque laborum quia placeat at qui aut.\n\nEt veritatis molestiae quos labore dolor nesciunt iusto. Quae et ipsum laborum quia. Quia sunt voluptas rerum ut id dolorem sapiente.\n\nQuibusdam laborum soluta dolorem optio ut qui. Quis aspernatur magni beatae illum exercitationem incidunt iure doloribus. Quod deleniti et perferendis esse sapiente totam. Voluptas atque non est neque.\n\nSit alias tempora velit sunt doloremque facilis similique consequatur. Et officia ex neque fugiat recusandae est eaque. Assumenda sit nemo ea necessitatibus aperiam.\n\nVel excepturi minima architecto similique esse. Est quia voluptatem culpa repellendus voluptas libero recusandae. Soluta optio molestiae ut facilis commodi ut et. Sunt voluptatem accusantium nobis ducimus quos at a repudiandae.\n\nEst velit magnam et. Ut ad recusandae aliquid veritatis repellat repudiandae a. Delectus aut aut quaerat voluptas minus facilis rerum. Ea sed eveniet ex aperiam earum dolores. Quod rerum dolores perferendis iste.\n\nQuia est non quibusdam odio molestiae. Molestiae veritatis asperiores sunt velit impedit commodi. Perspiciatis doloribus facere molestias minus quam eum. Totam nobis iste et reprehenderit esse culpa.\n\nLaboriosam assumenda magnam eos voluptate ad voluptatem voluptatem. Maiores sequi blanditiis tempore provident.\n\nVelit nulla reiciendis cupiditate quidem vitae commodi mollitia sequi. Ut eaque officia aut illo neque quasi occaecati ipsum. Accusantium nulla iure et illo dolores.\n\nNam velit facere et. Nisi expedita dolores et dolorem. Doloremque beatae inventore et iste aperiam magni. Dolor ut autem omnis qui mollitia eligendi totam.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(11, 'Eos repellat molestiae omnis cupiditate sed.', 'Et adipisci delectus laborum doloribus. Debitis perspiciatis dolorem ut ut sed eveniet expedita.', 'Nihil error esse corporis odit animi omnis distinctio sit. Ratione ipsum placeat modi corrupti voluptas incidunt autem. Provident expedita alias est rerum.\n\nOdit excepturi quia dolorem quae. Fuga consequatur quo est neque consequatur. Ab minima repellendus enim distinctio.\n\nCorporis aspernatur iure est quia a. Illum natus voluptatem ut et voluptatum.\n\nTemporibus nesciunt omnis fugit. Saepe magni animi et illo sed. Quae voluptate beatae recusandae et et a commodi. Non nihil maiores quaerat placeat iure hic dolorem.\n\nSit dolores adipisci ratione deserunt velit distinctio ut delectus. Saepe rem facilis magnam sed adipisci nihil expedita. Velit praesentium natus reprehenderit nobis. Illum blanditiis quidem dolore corporis ipsum.\n\nFuga fugit ullam perspiciatis adipisci ut velit eaque deserunt. Ad maxime est aspernatur ut sit harum. Voluptas et dolor debitis incidunt.\n\nQuia sapiente aliquid et laudantium quis. Omnis non voluptatem nesciunt sed omnis animi. Vel et ut enim quo maiores temporibus et.\n\nQuo aspernatur illo enim voluptatem mollitia. Officia nostrum odit veritatis ipsum. Rerum doloremque et eaque aliquam. Iste officia ut velit ab.\n\nVoluptas soluta sunt sit fuga neque dolor sunt. Et nihil aut provident eos. Aspernatur quos sit natus doloremque.\n\nSed deleniti neque et sunt sed aut. At ut aspernatur temporibus fugit et. Placeat ipsum commodi corrupti consequuntur deleniti quasi odio.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(26, 'salut', 'jsjsjssls', 'sskskksjjs', 'articles/20230620023016.png', '2023-06-20 01:30:16', '2023-06-20 01:30:16'),
(13, 'Suscipit veniam sequi impedit error.', 'Ut suscipit eos non et. Eaque ab corporis a optio eaque itaque. Vel maxime sit voluptatibus atque qui error expedita. Consequuntur molestias facere exercitationem iure et. Doloribus voluptate eos quas.', 'Minus rerum et provident animi suscipit. Et ratione perferendis sed tenetur aspernatur. Porro perspiciatis distinctio iusto quia quis iusto hic.\n\nQuibusdam est corrupti vel repellendus. Inventore qui similique velit doloribus exercitationem. Perspiciatis non facere dolorem nobis.\n\nRepellendus sed sint nemo quibusdam. Adipisci et est voluptas quae occaecati. Beatae id voluptas dolorem aut repellat. Qui et rem aut placeat.\n\nEum blanditiis pariatur porro. Praesentium dolorum aut est iste molestiae. Voluptatibus ullam dolore sit voluptatem dolorem. Maiores quod repellat id eum quia qui.\n\nVoluptatem voluptatem iusto nulla modi impedit odio. Dolores similique et consequatur voluptate voluptas voluptas. Labore libero quos ab.\n\nNostrum id nulla possimus non. Rerum nihil omnis repellat aut soluta. Consectetur eum corrupti vero voluptas est voluptas.\n\nLibero saepe a dolorem. Officiis officia aut ea. Repellat sunt cumque ut et.\n\nQui non consequatur explicabo dolorem deleniti harum odio. Omnis similique consectetur ab recusandae sunt ex officia. Corrupti itaque non recusandae ducimus accusantium voluptas. Consequatur dolor minus fuga necessitatibus.\n\nEum iusto pariatur non cum velit et. Ipsam sed repellat blanditiis impedit. Quia dolorum rem rerum modi minima nihil fugit.\n\nQui consequatur occaecati repudiandae voluptates consectetur corporis. Nulla amet hic ipsam ut. Perferendis consequuntur hic eaque similique voluptas molestiae eos. Voluptates quia qui dicta libero eveniet provident unde.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(14, 'Dolor corrupti suscipit totam sunt.', 'Odio repellendus necessitatibus consequatur aut voluptate quas exercitationem. Omnis incidunt incidunt sit consectetur eveniet ut.', 'Et sit tempore dolorem. Voluptatibus a et earum qui. Perspiciatis voluptas ea qui placeat laborum incidunt error. Sint non ex assumenda vitae esse natus.\n\nSunt sint neque molestiae quod. Cupiditate molestiae sed praesentium hic voluptatibus quis officia. Sequi vel voluptas sequi repellendus consequuntur exercitationem quidem non. Tempore dignissimos exercitationem culpa illum.\n\nExplicabo delectus unde eligendi perferendis dolorem dolor. Eos quidem sunt rem aliquam esse recusandae aut. Quisquam autem ipsum architecto. Animi corrupti dolorem saepe aspernatur eligendi eum.\n\nVoluptatum quaerat aperiam deleniti esse voluptatem quia. Architecto qui autem non sed necessitatibus dolorem quidem autem.\n\nAutem voluptas nesciunt et culpa repellendus. Omnis reiciendis nesciunt doloribus ex dolore aut deleniti cupiditate.\n\nPorro recusandae nobis consequuntur et sit. Porro laudantium reprehenderit et. Nihil mollitia repudiandae quos delectus.\n\nItaque qui commodi quae facilis non ea. Possimus nisi tempora est excepturi nihil. Vero reprehenderit corporis sit ut ab aspernatur.\n\nOfficia est tempora voluptas aspernatur cum. Dolore eveniet debitis numquam nesciunt fugit velit. Culpa rerum cupiditate ipsa voluptatem. Totam amet dolorum totam dolor consectetur omnis.\n\nCorporis labore placeat magnam qui ab sit dolorem. Vero aut doloremque rerum est et dolorem. Et voluptate ad praesentium voluptatum placeat omnis deserunt ratione.\n\nNihil eos nam et et quis. Suscipit quaerat assumenda sit temporibus officia. Adipisci et inventore unde similique atque sed molestiae quisquam. Pariatur dolore omnis tempora fugiat. Sint voluptatem ipsam eum quis voluptates nihil.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(15, 'Nisi odio minima tempore.', 'Perferendis aliquid et facere asperiores maiores natus atque. Quisquam quibusdam omnis tempora qui hic laborum. Neque praesentium neque possimus consequatur.', 'Dolorem omnis asperiores quisquam ex. Sit est quis laboriosam. Temporibus odit ex iure porro repudiandae. Nobis atque excepturi dicta qui.\n\nAnimi veritatis quidem dolores quo minus voluptatem repudiandae. Reiciendis delectus sapiente corporis fuga et voluptas consequatur. Soluta eius vero non vel iusto iure quidem sunt. Beatae distinctio cupiditate laudantium illum officia.\n\nQuis laudantium est hic hic odit. Sed quae dolore impedit. In libero dicta dignissimos maxime quisquam impedit. Repudiandae alias assumenda expedita est.\n\nMolestiae labore quis in eos soluta. Pariatur veniam in atque dignissimos distinctio. Harum sunt consequatur dicta qui libero in. Laboriosam qui eum tenetur dolores vitae excepturi optio sed.\n\nCupiditate illo quia iste qui. Est voluptatum dolores illum qui quod nobis. Nihil autem inventore nam dignissimos sed. Rerum veniam eveniet in sint odio doloremque et et. Quo et et occaecati non est excepturi optio.\n\nEt voluptas laboriosam omnis molestias. Aut qui ea et. Quas suscipit soluta vitae accusamus est eum.\n\nConsequatur velit quasi ea exercitationem eum voluptas. Iste blanditiis ex natus. Maiores porro eum esse nulla nam quos adipisci. Quam nostrum aut facere quod quis.\n\nNulla laboriosam et molestiae reiciendis soluta est. Asperiores sit dolores officia laudantium error. Sit minus deleniti magni accusamus eos neque aut.\n\nNatus fugiat veritatis consequatur sit. Blanditiis optio facilis molestiae sit fuga amet. Aut in rerum est sunt ad est.\n\nSapiente suscipit laudantium corrupti aut dolore esse. Animi fuga voluptate iusto molestias. Sint occaecati eius non qui excepturi velit.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(16, 'Quidem a id accusantium aperiam.', 'Deleniti consequatur et et qui ad rerum. Magni consequatur quam quia est dolorem sint molestiae. Dolorem aut officia distinctio unde. Id aperiam et sequi esse est alias praesentium.', 'Quasi veniam architecto et nulla necessitatibus enim. Beatae rerum enim sed aut in omnis alias. Recusandae provident qui est debitis assumenda et provident. Quaerat ad in tempora perspiciatis non enim libero dignissimos.\n\nAut tenetur reiciendis sed dolor. Cupiditate omnis quis consequatur.\n\nImpedit animi aut provident quo ut molestias porro aut. Amet aspernatur ducimus dolor est labore. Fuga accusantium quo nostrum aut et.\n\nAutem hic doloribus excepturi hic. Quos harum voluptate quibusdam maxime ut. Ullam ea consequatur id dolor eaque odit porro et. Autem officiis at qui magnam similique ipsum. Error ut sunt enim est magni.\n\nEst itaque dolore autem et optio natus maiores. Numquam labore voluptas enim architecto sint. Distinctio sit est deleniti aut. Accusamus quae facere repellat quidem enim. Eos ut provident voluptas cupiditate nam voluptatem.\n\nDoloremque officia ipsum voluptas itaque rerum totam quo. Dolorem voluptatem magnam ducimus dolor delectus ut quas enim. Dolorem quasi iure reiciendis tempora aliquam velit est. Maiores eaque nihil excepturi. Voluptates placeat vitae tempore eveniet cumque omnis.\n\nPerferendis perferendis doloremque debitis ut assumenda omnis voluptatibus. Qui laudantium similique fuga sit et expedita. Voluptas accusamus vel est dolore velit.\n\nAut minima quis quo non nihil. Vitae quas incidunt fugit animi. Eius recusandae eaque harum dolores et iste. A voluptatem consequuntur architecto tempora architecto.\n\nSapiente voluptate non sunt occaecati inventore quo ipsa. Sed et libero voluptatum voluptatibus voluptates nam accusamus labore. Quas quia doloremque repellat optio architecto unde. Minima pariatur quod laudantium sed excepturi similique eum. Corporis ullam necessitatibus porro rerum itaque dicta.\n\nTempore ea qui cum ut non delectus modi. Placeat quia ipsam accusamus sunt repellendus voluptas est. Est exercitationem fugit doloribus ratione quia odit consequatur.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(17, 'Et porro aut est quia.', 'Quia nulla excepturi impedit libero ut at totam. Autem id amet deserunt modi. Animi voluptates cumque animi qui ut. Consectetur voluptatem a sapiente aliquid impedit.', 'Sint ut et alias ducimus consectetur nostrum quia. Mollitia repellat dolorum voluptates ut quia qui. Est iusto earum doloribus sunt voluptates architecto. Error et laboriosam ducimus. Est sunt officiis dolores illum et sed.\n\nUt voluptas nulla quas fugit et et. Atque fugiat sit sed nihil qui ut quis ut. Quis ipsum enim minima vitae ipsam laudantium. Autem nesciunt adipisci illum alias sint nemo.\n\nEt placeat sunt blanditiis porro distinctio cum. Ea consectetur ipsam et porro. Tempore tenetur voluptas architecto in.\n\nOptio facere sunt quidem ea repellendus provident et nam. Vitae omnis minima inventore nobis tenetur distinctio.\n\nSed dolorum voluptas reprehenderit ratione suscipit laborum. Eligendi officia quod quo provident. Libero eum quia accusantium nam sed eum.\n\nAliquam vero commodi nam incidunt nostrum unde voluptas. Dolor porro iste recusandae dolorem illo vel. Suscipit quia numquam deleniti cupiditate inventore. Itaque autem nam rerum in officia quia quam.\n\nDicta ad quia error. Quo reiciendis consequatur et enim similique nulla. Recusandae et reprehenderit expedita tempore totam nobis fugiat. Et distinctio sint velit consequatur ullam.\n\nLaboriosam est earum sint inventore nisi. Libero velit neque debitis ipsa molestiae magni. Possimus eum non est quidem consequatur. Corrupti rerum ut omnis occaecati voluptatem aperiam et.\n\nExpedita culpa cumque delectus qui adipisci et eum. Nobis saepe repudiandae dolor occaecati sint quaerat.\n\nInventore voluptates unde reiciendis adipisci error. Velit doloribus qui doloribus repellendus beatae repellat perspiciatis consequatur. Dignissimos sit nostrum voluptatem laboriosam sapiente possimus. Aut ex debitis aut.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(18, 'Ut sunt recusandae veniam nostrum velit.', 'Laboriosam sunt et nobis distinctio eveniet et quia. Et qui quos culpa consequatur.', 'Quia et totam cum temporibus dolorem sequi. Soluta aut mollitia et voluptatibus. Atque velit unde quo odio.\n\nAd modi illo non sed qui dolorum porro quis. Ut voluptatem enim quas aut quia. Aut et error et. In nulla dolorem sapiente nesciunt. Omnis sit laboriosam tenetur temporibus id.\n\nEst doloribus aperiam voluptas nemo. Cupiditate eius nam corrupti vitae neque. Ut vel repudiandae quo quod eos.\n\nEst dolor error iure. At fuga laborum molestiae impedit cum est perspiciatis. Officiis numquam sed accusantium rerum atque. Numquam et qui distinctio iusto voluptatem.\n\nEt harum quidem architecto ab accusantium ut velit eos. Quae et facilis nisi accusamus impedit. Saepe mollitia et aut quaerat dolore ut.\n\nNeque non itaque repudiandae illum ex esse. Doloribus dolorum sit rem. Delectus fugit dolore rerum est. Non eum aut delectus vero aspernatur.\n\nQui possimus velit corrupti. Commodi laborum sunt repellat sunt dolorem. Fuga ut itaque ut voluptas autem voluptatum ut. Velit soluta at explicabo ipsam omnis veritatis.\n\nUllam tempora qui numquam laborum ut debitis. Officia vitae dolorem quia sit iure. Sit cupiditate qui aliquid laudantium. Non repellendus sed omnis magni officia repellat laborum.\n\nAlias ducimus vel facilis maiores voluptatem commodi facilis. Voluptatem fugiat itaque est voluptatem architecto non expedita quaerat. Harum quasi soluta adipisci sit occaecati deserunt. Vel et incidunt et veniam dolores.\n\nQuae saepe cumque sit cupiditate similique ratione fugit. Impedit natus laboriosam a voluptatem. Maiores ut delectus molestias voluptates. Impedit aliquid voluptate in dicta sed.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(19, 'Tempore qui id ratione illo ut.', 'Fuga sequi sunt rerum libero aut. Non dolorem dolorem eum accusamus placeat. Necessitatibus omnis maiores vitae rem consequuntur dolores nulla. Ea esse voluptates aut libero recusandae.', 'Expedita sit eum dignissimos voluptatem dignissimos. Id consectetur officiis atque.\n\nEos nesciunt perferendis eos eum ea qui corporis. Maiores culpa voluptatum labore qui tenetur odit. Ab est et asperiores soluta culpa et sunt laborum.\n\nUnde cumque sit eius maxime aut voluptatem. Autem necessitatibus qui voluptatem mollitia. Facere autem occaecati dolorum error est commodi.\n\nUt sed nisi quis eaque non quas. Illo voluptas sequi et est. Voluptas voluptatibus aut laudantium quod aspernatur sunt.\n\nDolorem neque laboriosam et harum quam ex et. Fugiat aliquid suscipit dolorem. Alias ut id voluptatem veritatis consequatur. Consequuntur blanditiis est qui incidunt.\n\nRerum est delectus porro aut. Deserunt non distinctio dolores vel explicabo. Ipsa ullam voluptas voluptate incidunt quasi expedita autem.\n\nPariatur sint deleniti et nostrum doloremque doloribus iure. Qui esse et repellat omnis molestiae qui. Aliquid provident accusantium et. Asperiores sapiente aspernatur quos illo voluptas quam cum dolorem.\n\nEst consequatur occaecati qui. Aut temporibus ut modi quo. Eligendi ea et sed reiciendis esse. Eaque dolore et dolor qui nobis.\n\nInventore autem reprehenderit et reprehenderit. Aut cupiditate magnam deserunt qui eum. Illo rerum consequatur quia consequatur ullam ipsam sapiente quae.\n\nNemo fugiat qui numquam aut iusto et nobis. Quas cupiditate dicta accusantium. Optio est est possimus itaque. Dolor necessitatibus voluptatem amet autem.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(20, 'Consequatur ut quisquam voluptatem animi.', 'Veritatis magni exercitationem optio esse quod numquam. Maxime animi accusantium voluptatibus ut delectus. In debitis magnam qui quam et et. Odit mollitia libero reiciendis et.', 'Rerum ut dolorem modi officiis commodi et ipsam ut. Ab iusto non earum nisi aspernatur asperiores. Et animi aspernatur magni hic quia ut.\n\nNihil eligendi quis magni quidem. Nihil sunt est quas debitis in. Soluta voluptates nostrum consequatur odio et rerum vitae. Sit maxime reiciendis omnis omnis.\n\nEt adipisci ex ducimus. Eum et molestias voluptatem numquam. Ut quisquam ratione qui in aliquam voluptas.\n\nUt incidunt ad amet et sed. Et natus tenetur unde placeat ullam provident dolores. Voluptates quo provident recusandae vero ut error est atque. Nisi quisquam delectus reprehenderit mollitia dolorem illum.\n\nEst quasi qui quia cum qui temporibus vitae. Eius qui facilis ducimus et dolores. Eos est itaque molestiae deserunt voluptatem quasi saepe. Consequatur est explicabo est et provident deserunt.\n\nQui impedit maiores ut recusandae. Dicta deserunt a aut nihil harum occaecati quos officia. Ut pariatur dolorem corporis ipsum pariatur inventore. Et quam quas facilis odit maiores et. Soluta tenetur alias minus dolorem ea ducimus.\n\nReiciendis dolor et placeat repellendus aspernatur voluptates. Enim dolore nostrum non est cumque voluptatibus voluptatum. Sit dolorem aut fugit et.\n\nQuo rerum explicabo veniam ipsum doloribus sit. Eius fugiat et deleniti modi et et non. Deleniti voluptatem ea eius quis nam aut. Est molestias repellat ratione nihil est. Animi voluptates est temporibus soluta.\n\nEnim magnam deleniti nihil nulla et. Ipsa a inventore est in aut.\n\nQui deserunt aliquid est quam. Aut quod maiores est consequatur id cupiditate.', NULL, '2023-01-10 09:01:52', '2023-01-10 09:01:52'),
(21, 'jjsjjsjsmmmmmmmmmmmmm', 'ksksksks', 'skkskssks', NULL, '2023-01-10 13:38:44', '2023-01-11 11:52:10'),
(24, 'test', 'shshs', 'snssj', NULL, '2023-01-11 12:12:19', '2023-01-11 12:12:19'),
(25, 'zzzz', 'zzz', 'zzzzzz', 'articles/20230111014155.png', '2023-01-11 12:41:56', '2023-01-11 12:41:56');

-- --------------------------------------------------------

--
-- Structure de la table `comments`
--

DROP TABLE IF EXISTS `comments`;
CREATE TABLE IF NOT EXISTS `comments` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `auteur` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `article_id` bigint(20) UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `comments_article_id_foreign` (`article_id`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `comments`
--

INSERT INTO `comments` (`id`, `auteur`, `content`, `article_id`, `created_at`, `updated_at`) VALUES
(1, 'willbe', 'jsjsjsjssssssssssssssss', 25, '2023-01-11 14:13:56', '2023-01-11 14:13:56'),
(2, 'willbe', 'jsjsjsjssssssssssssssss', 25, '2023-01-11 14:14:16', '2023-01-11 14:14:16'),
(3, 'jdjdjd', 'kkddkdkd', 24, '2023-01-11 14:17:43', '2023-01-11 14:17:43'),
(4, 'willbe', 'cooll', 15, '2023-01-12 12:41:19', '2023-01-12 12:41:37'),
(5, 'willbe', 'llkkkk', 14, '2023-01-12 12:56:21', '2023-01-12 12:56:21'),
(6, 'djjd', 'djdjjdd', 25, '2023-06-20 01:31:01', '2023-06-20 01:31:01');

-- --------------------------------------------------------

--
-- Structure de la table `failed_jobs`
--

DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `migrations`
--

DROP TABLE IF EXISTS `migrations`;
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(5, '2023_01_10_083207_create_articles_table', 1),
(6, '2023_01_11_143122_create_comments_table', 2);

-- --------------------------------------------------------

--
-- Structure de la table `password_resets`
--

DROP TABLE IF EXISTS `password_resets`;
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `personal_access_tokens`
--

DROP TABLE IF EXISTS `personal_access_tokens`;
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
